name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: market-immune-system
  REGION: us-central1
  SERVICE_NAME: market-immune-system

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Authorize Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-lib/market-immune-system:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-lib/market-immune-system:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: market-immune-system
          region: us-central1
          image: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-lib/market-immune-system:${{ github.sha }}
          env_vars: |-
            FRED_API_KEY=${{ secrets.FRED_API_KEY }}

